### ISSUE TITLE
Upchage input box

### ISSUE THREAD

**Issue by nEwwAke** [blackboardd/xps-upcharge#7]
Upcharge % percent input box does not keep size across browsers.

On Firefox Linux shows single digit.  (Is 70.)
![xps upcharge percent box](https://user-images.githubusercontent.com/92280458/139989995-6fbb8dab-82f1-4869-a0f8-e010e8418e9c.png)

**Comment by blackboardd** [comment]
This issue has been corrected in a newer version. 2.1.0 does not have this issue.
